[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.68",
    "fastapi[standard]>=0.140.13",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.12",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy>=2.0.51",
]

[build-system]
requires = ["uv_build>=0.9.2,<0.10"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
namespace = false
